config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts
  delete 'posts/:id/file_attachments/:blob_id', to: 'posts#delete_file_attachment', as: :delete_post_file_attachment
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content
  has_many_attached :files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy,  :delete_file_attachment]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_file_attachment
    attached_file = ActiveStorage::Attachment.find_by blob_id: params[:blob_id]
    attached_file.purge_later
    # redirect_back(fallback_location: @admin_note)
    respond_to do |format|
      format.js
    end
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, files: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  STYLES = {
    regular: 'r',
    solid: 's',
    brands: 'b',
    light: 'l',
    duotone: 'd'
  }.freeze

  def fa_icon(style, fontname)
    content_tag(:i, '', class: "fa#{STYLES[style]} fa-#{fontname}")
  end 
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]), data: { target: 'fancybox.blob', caption: blob.filename, url: rails_blob_path(blob) } %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="field">
    <%= label_tag 'Attachment Files' %>
    <div class='alert alert-secondary'>
      <div id="preview_file_attachments" style='height:auto;'>
        <%= render 'preview_file_attachment', post: form.object %>
      </div>
      <div class="custom-file" data-controller='file-upload' style='height: auto;'>
        <%= form.file_field :files, multiple: true, id: 'customFile', class: 'custom-file-input', data: { target: 'file-upload.files'} %>
        <%= form.label :files, 'Choose Files', for: 'customFile', class: 'custom-file-label' %>
      </div>
    </div>
  </div> 

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_preview_embeds.html.erb
<% if post.content.embeds.size.positive? %>
  <div>삽입된 파일(<%= post.content.embeds.size %>) :</div>
  <% post.content.embeds.each do |file| %>
    <% if file.representable? %>
      <div style="display:inline-block;position: relative;width:100px;height:100px;margin: 3px;">
        <% if file.content_type.include? 'image'%>
          <%= link_to image_tag(file.variant(resize_to_fill: [100, 100]), class: 'img-fluid rounded'), file, download: true, class: 'border border-primary d-inline-block rounded' %>
        <% else %>
            <%= link_to image_tag(file.preview(resize_to_fill: [100, 100]), class: 'img-fluid rounded'), file, download: true, class: 'border border-primary d-inline-block rounded' %>
        <% end %>
      </div>
    <% else %>
      <%= link_to file.filename, file, download: true, class: 'btn btn-secondary' %>
    <% end %>
  <% end %>
<% end %>

app/views/posts/_preview_file_attachment.html.erb
<% if post.files.attached? %>
  <div>첨부된 파일(<%= post.files.size %>) :</div>
  <% post.files.each do |file| %>
    <% if file.content_type.include? 'image' %>
      <div class='file-thumbnail'>
          <% if file.content_type.include? 'image'%>
            <%= link_to image_tag(file.variant(resize_to_fill: [100, 100]), class: 'img-fluid rounded'), file, data: { fancybox: 'gallery', caption: file.filename }  %>
          <% else %>
              <%= link_to image_tag(file.preview(resize_to_fill: [100, 100]), class: 'img-fluid rounded'), file  %>
          <% end %>
          <%= link_to fa_icon(:solid, 'trash'), delete_post_file_attachment_path(post.id, file.blob_id),
                method: :delete,
                remote: true,
                data: { confirm: 'Are you sure?' },
                class: 'text-danger',
                style: 'position: absolute; top: 0; right: 0; margin-right: 4px;' %>
      </div>
    <% end %>
  <% end %>
  <ul class="list-group mt-2">
    <% post.files.each do |file| %>
      <% unless file.content_type.include? 'image' %>
        <li class="list-group-item">
          <%= fa_icon(:solid, 'download') %> <%= link_to file.filename, file %>
          <%= link_to fa_icon(:solid, 'trash'), delete_post_file_attachment_path(post.id, file.blob_id),
                  method: :delete,
                  remote: true,
                  data: { confirm: 'Are you sure?' },
                  class: 'text-danger' %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/posts/delete_file_attachment.js.erb
$("#preview_file_attachments").html("<%=j render 'preview_file_attachment', post: @post %>")

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>

<hr>

<h2>
  Bootstrap Tooltips
</h2>
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
  Tooltip on top
</button>
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="right" title="Tooltip on right">
  Tooltip on right
</button>
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="bottom" title="Tooltip on bottom">
  Tooltip on bottom
</button>
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="left" title="Tooltip on left">
  Tooltip on left
</button>

<hr>

<h2>
  Bootstrap Popovers
</h2>
<button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="top" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">
  Popover on top
</button>

<button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="right" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">
  Popover on right
</button>

<button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="bottom" data-content="Vivamus
sagittis lacus vel augue laoreet rutrum faucibus.">
  Popover on bottom
</button>

<button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="left" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">
  Popover on left
</button>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <div data-controller='fancybox'>
    <%= @post.content %>
  </div>
</p>

<div id="preview_file_attachments" class='my-3' data-controller='fancybox'>
  <%= render 'preview_embeds', post: @post %>
</div>

<div id="preview_file_attachments" class='my-3' data-controller='fancybox'>
  <%= render 'preview_file_attachment', post: @post %>
</div>

<hr>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>